CREATE TABLE IF NOT EXISTS admin_pin_settings (
  app_user_id UUID PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
  pin_hash TEXT NOT NULL CHECK (length(pin_hash) >= 64),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
